[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives of messages module."
edition     = "2018"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-messages"
version     = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

# Bridge dependencies

bp-runtime = { path = "../runtime", default-features = false }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3", default-features = false }
frame-system  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3", default-features = false }
sp-std        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3", default-features = false }

[features]
default = ["std"]
std = [
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"sp-std/std",
]
