[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives of messages module."
edition     = "2021"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-messages"
version     = "0.1.0"

[dependencies]
# crates.io
bitvec                = { version = "1", default-features = false, features = ["alloc"] }
codec                 = { package = "parity-scale-codec", version = "2.3", default-features = false, features = ["derive", "bit-vec"] }
impl-trait-for-tuples = { version = "0.2" }
scale-info            = { version = "1.0", default-features = false, features = ["bit-vec", "derive"] }
serde                 = { version = "1.0", optional = true, features = ["derive"] }
# darwinia-network
bp-runtime = { default-features = false, path = "../runtime" }
# paritytech
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-core       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }

[dev-dependencies]
array-bytes = { version = "4.1" }

[features]
default = ["std"]
std = [
	# crates.io
	"bitvec/std",
	"codec/std",
	"scale-info/std",
	"serde",
	# darwinia-network
	"bp-runtime/std",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
]
