[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Module that allows bridged chains to exchange messages using lane concept."
edition     = "2021"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "pallet-bridge-messages"
version     = "0.1.0"

[dependencies]
# crates.io
bitvec     = { version = "0.20", default-features = false, features = ["alloc"] }
codec      = { package = "parity-scale-codec", version = "2.3", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde      = { version = "1.0", optional = true, features = ["derive"] }
# darwinia-network
bp-message-dispatch = { default-features = false, path = "../../primitives/message-dispatch" }
bp-messages         = { default-features = false, path = "../../primitives/messages" }
bp-runtime          = { default-features = false, path = "../../primitives/runtime" }
# paritytech
frame-benchmarking = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
frame-support      = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
frame-system       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-core            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-runtime         = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-std             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }

[dev-dependencies]
# darwinia-network
bp-test-utils = { path = "../../primitives/test-utils" }
# paritytech
pallet-balances = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }
sp-io           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.13.0" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"num-traits/std",
	"scale-info/std",
	"serde",
	# darwinia-network
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-runtime/std",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]
