[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Module that allows bridged chains to exchange messages using lane concept."
edition     = "2021"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "pallet-bridge-messages"
version     = "0.1.0"

[dependencies]
# crates.io
bitvec     = { version = "0.20", default-features = false, features = ["alloc"] }
codec      = { version = "2.3", package = "parity-scale-codec", default-features = false }
log        = { version = "0.4.14", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde      = { version = "1.0.101", optional = true, features = ["derive"] }
# darwinia-bridges-substrate
bp-message-dispatch = { path = "../../primitives/message-dispatch", default-features = false }
bp-messages         = { path = "../../primitives/messages", default-features = false }
bp-runtime          = { path = "../../primitives/runtime", default-features = false }
bp-test-utils       = { path = "../../primitives/test-utils", default-features = false, optional = true }
# paritytech
frame-benchmarking = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false, optional = true }
frame-support      = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
frame-system       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-core            = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-runtime         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-std             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }

[dev-dependencies]
sp-io           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
pallet-balances = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"num-traits/std",
	"scale-info/std",
	"serde",
	# darwinia-network
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]
