[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-rialto-client"
version = "0.1.0"

[dependencies]
codec                  = { package = "parity-scale-codec", version = "2.2.0" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }

# Bridge dependencies

bp-rialto      = { path = "../../primitives/chain-rialto" }
rialto-runtime = { path = "../../bin/rialto/runtime" }

# Substrate Dependencies

frame-support              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
frame-system               = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
