[workspace]
resolver = "2"

members = [
	# "bin/*/node",
	# "bin/*/runtime",
	# "fuzz/*",
	"modules/*",
	"primitives/*",
	"relays/client-kusama",
	"relays/client-polkadot",
	"relays/client-rococo",
	"relays/client-substrate",
	"relays/finality",
	"relays/lib-substrate-relay",
	"relays/messages",
	"relays/utils",
]
