[package]
authors     = ["Parity Technologies <admin@parity.io>"]
build       = "build.rs"
description = "Substrate node compatible with Millau runtime"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "millau-bridge-node"
repository  = "https://github.com/paritytech/parity-bridges-common/"
version     = "0.1.0"

[dependencies]
clap         = { version = "3.0", features = ["derive"] }
jsonrpc-core = "18.0"
serde_json   = "1.0.59"

# Bridge dependencies

bp-millau              = { path = "../../../primitives/chain-millau" }
bp-runtime             = { path = "../../../primitives/runtime" }
millau-runtime         = { path = "../runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }

# Substrate Dependencies

beefy-gadget                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
beefy-gadget-rpc               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
beefy-primitives               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-benchmarking             = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-benchmarking-cli         = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
node-inspect                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-mmr-rpc                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-basic-authorship            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-cli                         = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", features = ["wasmtime"] }
sc-client-api                  = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus-aura              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-executor                    = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-finality-grandpa            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-finality-grandpa-rpc        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-keystore                    = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-rpc                         = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-service                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-telemetry                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-transaction-pool            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-consensus                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-consensus-aura              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-finality-grandpa            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-timestamp                   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
substrate-frame-rpc-system     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[build-dependencies]
frame-benchmarking-cli       = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[features]
default = []
runtime-benchmarks = [
	"millau-runtime/runtime-benchmarks",
]
