[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "substrate-relay-helper"
version = "0.1.0"

[dependencies]
anyhow      = "1.0"
async-std   = "1.9.0"
async-trait = "0.1.42"
codec       = { package = "parity-scale-codec", version = "2.2.0" }
futures     = "0.3.12"
log         = "0.4.14"
num-traits  = "0.2"
thiserror   = "1.0.26"


# Bridge dependencies

bp-header-chain       = { path = "../../primitives/header-chain" }
bridge-runtime-common = { path = "../../bin/runtime-common" }

finality-grandpa       = { version = "0.14.0" }
finality-relay         = { path = "../finality" }
messages-relay         = { path = "../messages" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }

pallet-bridge-grandpa  = { path = "../../modules/grandpa" }
pallet-bridge-messages = { path = "../../modules/messages" }

bp-messages = { path = "../../primitives/messages" }
bp-runtime  = { path = "../../primitives/runtime" }

# Substrate Dependencies

frame-support       = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-system        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-balances     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core             = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime          = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[dev-dependencies]
bp-millau           = { path = "../../primitives/chain-millau" }
bp-rialto           = { path = "../../primitives/chain-rialto" }
bp-rococo           = { path = "../../primitives/chain-rococo" }
bp-wococo           = { path = "../../primitives/chain-wococo" }
relay-rococo-client = { path = "../client-rococo" }
relay-wococo-client = { path = "../client-wococo" }
rialto-runtime      = { path = "../../bin/rialto/runtime" }
