[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives of bridge messages dispatch modules."
edition     = "2018"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-message-dispatch"
version     = "0.1.0"

[dependencies]
bp-runtime = { path = "../runtime", default-features = false }
codec      = { package = "parity-scale-codec", version = "2.2.0", default-features = false }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", branch = "main", default-features = false }
sp-std        = { git = "https://github.com/darwinia-network/substrate", branch = "main", default-features = false }

[features]
default = ["std"]
std = [
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"sp-std/std",
]
