[package]
authors    = ["Parity Technologies <admin@parity.io>"]
edition    = "2018"
homepage   = "https://substrate.dev"
license    = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name       = "rialto-parachain-collator"
repository = "https://github.com/paritytech/parity-bridges-common/"
version    = "0.1.0"

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

[[bin]]
name = 'rialto-parachain-collator'

[features]
default            = []
runtime-benchmarks = ['rialto-parachain-runtime/runtime-benchmarks']

[dependencies]
codec       = { package = 'parity-scale-codec', version = '2.0.0' }
derive_more = '0.99.2'
hex-literal = '0.3.1'
log         = '0.4.14'
serde       = { version = '1.0', features = ['derive'] }
structopt   = '0.3.8'

# RPC related Dependencies
jsonrpc-core = '18.0'

# Local Dependencies
rialto-parachain-runtime = { path = '../runtime' }

# Substrate Dependencies
frame-benchmarking     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
frame-benchmarking-cli = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

substrate-frame-rpc-system    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
substrate-prometheus-endpoint = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

## Substrate Client Dependencies
sc-basic-authorship = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-chain-spec       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-cli              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-client-api       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-consensus        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-executor         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-keystore         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-network          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-rpc              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-rpc-api          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-service          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0", features = ['wasmtime'] }
sc-telemetry        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-tracing          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-transaction-pool = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

## Substrate Primitive Dependencies
sp-api              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-block-builder    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-blockchain       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-consensus        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-consensus-aura   = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-core             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-inherents        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-keystore         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-offchain         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-session          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-timestamp        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-transaction-pool = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }

# Cumulus dependencies
cumulus-client-cli                    = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-collator               = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-consensus-aura         = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-consensus-common       = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-network                = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-service                = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-primitives-core               = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "master" }

# Polkadot dependencies
polkadot-cli          = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-parachain    = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-primitives   = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-service      = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }
