[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-substrate-client"
version = "0.1.0"

[dependencies]
async-std             = { version = "1.6.5", features = ["attributes"] }
async-trait           = "0.1.40"
codec                 = { package = "parity-scale-codec", version = "2.2.0" }
futures               = "0.3.7"
jsonrpsee-proc-macros = "0.3.1"
jsonrpsee-ws-client   = "0.3.1"
log                   = "0.4.11"
num-traits            = "0.2"
rand                  = "0.7"
thiserror             = "1.0.26"
tokio                 = "1.8"

# Bridge dependencies

bp-header-chain        = { path = "../../primitives/header-chain" }
bp-messages            = { path = "../../primitives/messages" }
bp-runtime             = { path = "../../primitives/runtime" }
finality-relay         = { path = "../finality" }
pallet-bridge-messages = { path = "../../modules/messages" }
relay-utils            = { path = "../utils" }

# Substrate Dependencies

frame-support                              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
frame-system                               = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
pallet-balances                            = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
pallet-transaction-payment                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sc-rpc-api                                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sc-transaction-pool-api                    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-core                                    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-finality-grandpa                        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-rpc                                     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-runtime                                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-storage                                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-trie                                    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }
sp-version                                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.1" }

[features]
default      = []
test-helpers = []
