[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "bp-test-utils"
version = "0.1.0"

[dependencies]
bp-header-chain = { path = "../header-chain", default-features = false  }
codec = { package = "parity-scale-codec", version = "2.3", default-features = false }
ed25519-dalek = { version = "1.0", default-features = false, features = ["u64_backend"] }
finality-grandpa = { version = "0.14", default-features = false }
sp-application-crypto = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false  }
sp-runtime = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-std = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }


# paritytech
[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"ed25519-dalek/std",
	"finality-grandpa/std",
	# darwinia-network
	"bp-header-chain/std",
	# paritytech
	"sp-application-crypto/std",
	"sp-finality-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
]
