[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives that may be used at (bridges) runtime level."
edition     = "2021"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-runtime"
version     = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
trie-db    = { version = "0.24", default-features = false }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
frame-system = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-core = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-io = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-runtime = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-state-machine = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-std = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-trie = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }

[dev-dependencies]
# crates.io
array-bytes = { version = "4.1" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"hash-db/std",
	"num-traits/std",
	"trie-db/std",
	"scale-info/std",
	"serde",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	# "trie-db/std",
]
