[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "Primitives of parachains module."
edition     = "2018"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-parachains"
version     = "0.1.0"

[dependencies]
codec      = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde      = { version = "1.0", optional = true, features = ["derive"] }

# Bridge dependencies

bp-polkadot-core = { path = "../polkadot-core", default-features = false }
bp-runtime       = { path = "../runtime", default-features = false }

# Substrate dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.3", default-features = false }
sp-core       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.3", default-features = false }

[features]
default = ["std"]
std = [
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
]
