[package]
name = "relay-kusama-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay = { path = "../headers" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils = { path = "../utils" }

# Bridge dependencies

bp-kusama = { path = "../../primitives/chain-kusama" }

# Substrate Dependencies

frame-system = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
frame-support = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
sp-core = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
sp-keyring = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate", tag = "s2s-v1.0" }
