[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-rialto-parachain-client"
version = "0.1.0"

[dependencies]
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }

# Bridge dependencies

bp-rialto                = { path = "../../primitives/chain-rialto" }
rialto-parachain-runtime = { path = "../../bin/rialto-parachain/runtime" }

# Substrate Dependencies

frame-support              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
frame-system               = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
