[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-millau-client"
version = "0.1.0"

[dependencies]
codec                  = { package = "parity-scale-codec", version = "2.2.0" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }

# Supported Chains

bp-millau      = { path = "../../primitives/chain-millau" }
millau-runtime = { path = "../../bin/millau/runtime" }

# Substrate Dependencies

frame-support              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.5" }
frame-system               = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.5" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.5" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.5" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.5" }
