[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-rococo-client"
version = "0.1.0"

[dependencies]
codec                  = { package = "parity-scale-codec", version = "2.2.0" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }
scale-info             = { version = "1.0", features = ["derive"] }

# Bridge dependencies

bp-header-chain        = { path = "../../primitives/header-chain" }
bp-message-dispatch    = { path = "../../primitives/message-dispatch" }
bp-messages            = { path = "../../primitives/messages" }
bp-polkadot-core       = { path = "../../primitives/polkadot-core" }
bp-rococo              = { path = "../../primitives/chain-rococo" }
bp-runtime             = { path = "../../primitives/runtime" }
bp-wococo              = { path = "../../primitives/chain-wococo" }
bridge-runtime-common  = { path = "../../bin/runtime-common" }
pallet-bridge-dispatch = { path = "../../modules/dispatch" }
pallet-bridge-messages = { path = "../../modules/messages" }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-core       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-runtime    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
