[package]
authors     = ["Parity Technologies <admin@parity.io>"]
description = "A common interface for describing what a bridge pallet should be able to do."
edition     = "2021"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "bp-header-chain"
version     = "0.1.0"

[dependencies]
# crates.io
codec            = { package = "parity-scale-codec", version = "2.3", default-features = false }
finality-grandpa = { version = "0.14", default-features = false }
scale-info       = { version = "1.0", default-features = false, features = ["derive"] }
serde            = { version = "1.0", optional = true }
# darwinia-network
bp-runtime = { path = "../runtime", default-features = false }
# paritytech
frame-support       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-core             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }
sp-std              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5", default-features = false }

[dev-dependencies]
# crates.io
array-bytes    = { version = "4.1" }
assert_matches = { version = "1.5" }
bp-test-utils  = { path = "../test-utils" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"finality-grandpa/std",
	"scale-info/std",
	"serde/std",
	# darwinia-network
	"bp-runtime/std",
	# paritytech
	"frame-support/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
]
