[package]
authors    = ["Parity Technologies <admin@parity.io>"]
edition    = "2021"
license    = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name       = "bridge-runtime-common"
repository = "https://github.com/paritytech/parity-bridges-common/"
version    = "0.1.0"

[dependencies]
# crates.io
codec             = { package = "parity-scale-codec", version = "2.3", default-features = false, features = ["derive"] }
hash-db           = { version = "0.15", default-features = false }
num-traits        = { version = "0.2", default-features = false }
scale-info        = { version = "1.0", default-features = false, features = ["derive"] }
static_assertions = { version = "1.1", optional = true }
# darwinia-network
bp-message-dispatch      = { default-features = false, path = "../primitives/message-dispatch" }
bp-messages              = { default-features = false, path = "../primitives/messages" }
bp-polkadot-core         = { default-features = false, path = "../primitives/polkadot-core" }
bp-runtime               = { default-features = false, path = "../primitives/runtime" }
pallet-bridge-dispatch    = { default-features = false, path = "../modules/dispatch" }
pallet-bridge-grandpa    = { default-features = false, path = "../modules/grandpa" }
pallet-bridge-messages   = { default-features = false, path = "../modules/messages" }
pallet-bridge-parachains = { default-features = false, path = "../modules/parachains" }
pallet-fee-market        = { default-features = false, path = "../modules/fee-market" }
# paritytech
frame-support              = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
frame-system               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
pallet-balances            = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-api                     = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-core                    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-io                      = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-runtime                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-state-machine           = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-std                     = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-trie                    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-version                 = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }

[features]
default = ["std"]
std = [
	# darwinia-network
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"pallet-bridge-dispatch/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-parachains/std",
	"pallet-fee-market/std",
	# crates.io
	"codec/std",
	"hash-db/std",
	"num-traits/std",
	"scale-info/std",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
]

integrity-test = [
	"static_assertions",
]

runtime-benchmarks = [
	"pallet-balances",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-state-machine",
	"sp-version",
]
