[package]
authors     = ["Parity Technologies <admin@parity.io>"]
build       = "build.rs"
description = "Substrate node compatible with Rialto runtime"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "rialto-bridge-node"
repository  = "https://github.com/paritytech/parity-bridges-common/"
version     = "0.1.0"

[dependencies]
futures      = "0.3"
jsonrpc-core = "18.0"
kvdb         = "0.10"
kvdb-rocksdb = "0.12"
serde_json   = "1.0.59"
structopt    = "0.3.21"
thiserror    = "1.0"

# Bridge dependencies

bp-rialto              = { path = "../../../primitives/chain-rialto" }
bp-runtime             = { path = "../../../primitives/runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }
rialto-runtime         = { path = "../runtime" }

# Substrate Dependencies

frame-benchmarking                         = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
frame-benchmarking-cli                     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
frame-system-rpc-runtime-api               = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
node-inspect                               = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
pallet-transaction-payment-rpc             = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-authority-discovery                     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-basic-authorship                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-cli                                     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4", features = ["wasmtime"] }
sc-client-api                              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-consensus                               = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-consensus-babe                          = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-consensus-slots                         = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-consensus-uncles                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-executor                                = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-finality-grandpa                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-finality-grandpa-rpc                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
#sc-finality-grandpa-warp-sync = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-keystore                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-network                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-rpc                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-service                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-telemetry                  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sc-transaction-pool           = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-api                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-authority-discovery        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-authorship                 = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-block-builder              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-blockchain                 = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-consensus                  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-consensus-babe             = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-core                       = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-finality-grandpa           = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-inherents                  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-offchain                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-runtime                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-session                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-timestamp                  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
sp-transaction-pool           = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
substrate-frame-rpc-system    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
substrate-prometheus-endpoint = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }

# Polkadot (parachain) Dependencies

polkadot-approval-distribution              = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-availability-bitfield-distribution = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-availability-distribution          = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-availability-recovery              = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-collator-protocol                  = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-dispute-distribution               = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-gossip-support                     = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-network-bridge                     = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-collation-generation          = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-approval-voting          = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-av-store                 = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-backing                  = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-bitfield-signing         = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-candidate-validation     = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-chain-api                = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-chain-selection          = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-dispute-coordinator      = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-dispute-participation    = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-parachains-inherent      = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-provisioner              = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-pvf                      = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-core-runtime-api              = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-network-protocol              = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-node-subsystem-util                = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-overseer                           = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-primitives                         = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-runtime-parachains                 = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-statement-distribution             = { git = "https://github.com/paritytech/polkadot", branch = "master" }

[build-dependencies]
frame-benchmarking-cli       = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.4" }

[features]
default = []
runtime-benchmarks = [
	"rialto-runtime/runtime-benchmarks",
]
