[package]
authors     = ["Parity Technologies <admin@parity.io>"]
build       = "build.rs"
description = "Substrate node compatible with Rialto runtime"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "rialto-bridge-node"
repository  = "https://github.com/paritytech/parity-bridges-common/"
version     = "0.1.0"

[dependencies]
clap         = { version = "3.0", features = ["derive"] }
futures      = "0.3"
jsonrpc-core = "18.0"
kvdb         = "0.10"
kvdb-rocksdb = "0.12"
lru          = "0.7"
serde_json   = "1.0.59"
thiserror    = "1.0"

# Bridge dependencies

bp-rialto              = { path = "../../../primitives/chain-rialto" }
bp-runtime             = { path = "../../../primitives/runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }
rialto-runtime         = { path = "../runtime" }

# Substrate Dependencies

beefy-gadget                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
beefy-gadget-rpc                           = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
beefy-primitives                           = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-benchmarking                         = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-benchmarking-cli                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-system-rpc-runtime-api               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
node-inspect                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-mmr-primitives                      = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-mmr-rpc                             = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-transaction-payment-rpc             = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-authority-discovery                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-basic-authorship                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-cli                                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", features = ["wasmtime"] }
sc-client-api                              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus-babe                          = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus-slots                         = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-consensus-uncles                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-executor                                = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-finality-grandpa                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-finality-grandpa-rpc                    = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-keystore                                = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-network                                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-rpc                                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-service                                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-telemetry                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sc-transaction-pool                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-api                                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-authority-discovery                     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-authorship                              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-block-builder                           = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-blockchain                              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-consensus                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-consensus-babe                          = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core                                    = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-finality-grandpa                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-inherents                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-offchain                                = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime                                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-session                                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-timestamp                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-transaction-pool                        = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
substrate-frame-rpc-system                 = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
substrate-prometheus-endpoint              = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

# Polkadot Dependencies

polkadot-node-core-pvf      = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-primitives         = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-service            = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16", default-features = false, features = ["full-node", "polkadot-native"] }

[build-dependencies]
frame-benchmarking-cli       = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

[features]
default = []
runtime-benchmarks = [
	"rialto-runtime/runtime-benchmarks",
]
