[package]
authors     = ["Parity Technologies <admin@parity.io>"]
build       = "build.rs"
description = "Substrate node compatible with Rialto runtime"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name        = "rialto-bridge-node"
repository  = "https://github.com/paritytech/parity-bridges-common/"
version     = "0.1.0"

[dependencies]
jsonrpc-core = "15.1.0"
serde_json   = "1.0.59"
structopt    = "0.3.21"

# Bridge dependencies

bp-messages            = { path = "../../../primitives/messages" }
bp-rialto              = { path = "../../../primitives/chain-rialto" }
bp-runtime             = { path = "../../../primitives/runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }
rialto-runtime         = { path = "../runtime" }

# Substrate Dependencies


frame-benchmarking             = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
frame-benchmarking-cli         = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
node-inspect                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-basic-authorship            = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-cli                         = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3", features = ["wasmtime"] }
sc-client-api                  = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-consensus                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-consensus-aura              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-executor                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-finality-grandpa            = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-finality-grandpa-rpc        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-keystore                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-rpc                         = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-service                     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-telemetry                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sc-transaction-pool            = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-consensus                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-consensus-aura              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-core                        = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-finality-grandpa            = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-inherents                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-runtime                     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
sp-timestamp                   = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
substrate-frame-rpc-system     = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }

[build-dependencies]
frame-benchmarking-cli       = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.3" }
substrate-build-script-utils = "3.0.0"

[features]
default = []
runtime-benchmarks = [
	"rialto-runtime/runtime-benchmarks",
]
