name: Check pull request

on:
  push:
    branches: [main, darwinia-v*, polkadot-v*]
  pull_request:
    branches: [main, darwinia-v*, polkadot-v*]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package:
          - pallet-bridge-dispatch
          - pallet-fee-market
          - pallet-bridge-grandpa
          - pallet-bridge-messages
          - pallet-bridge-parachains
          - bp-crab
          - bp-crab-parachain
          - bp-darwinia
          - bp-kusama
          - bp-pangolin
          - bp-pangolin-parachain
          - bp-pangoro
          - bp-rococo
          - bp-darwinia-core
          - bridge-runtime-common
    steps:
      - uses: actions/checkout@v2
      - name: Check ${{ matrix.package }}
        run: cargo check -p ${{ matrix.package }}
      - name: Test ${{ matrix.package }}
        run: cargo test -p ${{ matrix.package }}
