name: Check pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy --release --all -- -D warnings
      - name: Run tests
        run: cargo test --release
